name: Build ARM64 Offline Image

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Export ARM64 Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/arm64
          outputs: type=docker,dest=./stock-arm64.tar
          tags: local-stock:latest

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: stock-arm64-image
          path: ./stock-arm64.tar
